from tkinter import *
s=Tk()
s.title("student registration form")
Label(s,text="Full Name").grid(row=1,column=0)
Label(s,text="age").grid(row=2,column=0)
Label(s,text="Gender").grid(row=3,column=0)
#creating radiobuttons
var1=IntVar()
Radiobutton(s,text="Male",variable=var1,value=1).grid(row=4,column=1,sticky=W)
var2=IntVar()
Radiobutton(s,text="Female",variable=var2,value=2).grid(row=5,column=1,sticky=W)
Label(s,text="email id").grid(row=6,column=0)
Label(s,text="Ph on").grid(row=7,column=0)
e1=Entry(s)
e2=Entry(s)
e3=Entry(s)
e4=Entry(s)
e1.grid(row=1,column=1)
e2.grid(row=2,column=1)
e3.grid(row=6,column=1)
e4.grid(row=7,column=1,)
Label(s,text="courses interested").grid(row=8,column=0)
#creating checkbox
Checkbutton(s,text="python").grid(row=9,column=1,sticky=W)
Checkbutton(s,text="java").grid(row=10,column=1,sticky=W)
Checkbutton(s,text="html").grid(row=11,column=1,sticky=W)
Checkbutton(s,text="javascript").grid(row=12,column=1,sticky=W)
s.mainloop()